Gh 105 reference points
SzFMV2021-Tavasz/AutomatedCar-A pull request #109
Opened 2021-03-11 09:51 UTC by kuklinistvan

Megoldja: #105

2021-03-11 10:04 UTC, kuklinistvan commented
@pintergreg Segítséget szeretnék kérni:
https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/pull/109/checks?check_run_id=2085156253

Csináltam egy pull-up refaktort: létrehoztam a `JSONDictionaryDeserializer` absztrakt osztályt. A codecov most nem enged merge-elni, mert azt állítja, hogy az absztrakt osztályt nem teszteltem. A leszármazott osztályokat azonban használom a tesztekben, ezért nem értem, pontosan mit szeretne.

A `World.cs`-ben is panaszkodik olyan sorokra, amiket egészen biztosan lefedtem, hiszen általában egy-egy sor került bele egy-egy függvénybe, aminek az egészét használta a teszt.

2021-03-12 11:25 UTC, kuklinistvan commented
@pintergreg? :)

2021-03-12 19:31 UTC, pintergreg commented on src/AutomatedCar/Assets/reference_points.json
> -    "name": "road_2lane_rotary.png",
Ehhez más, nem nyúl csak ti, igaz? Tehát nem fog pl. a @SzFMV2021-Tavasz/team-a4 arra számítani, hogy ott van benne a png is.

2021-03-12 19:45 UTC, pintergreg commented
Első nekifutásra nem tudom, jobban bele kell mennem a kiszámítás módjába.

Workaround: a Codecov check nem kötelező (required), nem blokkolja a merge-elést.

2021-03-14 11:59 UTC, Sumakolo approved these changes

2021-03-14 12:06 UTC, vajnaivik submitted a review, later dismissed

2021-03-14 13:17 UTC, kuklinistvan commented on src/AutomatedCar/Assets/reference_points.json
> -    "name": "road_2lane_rotary.png",
Elvileg nem kellene, hiszen ez a fájl csak a referencia pontokat tartalmazza, amiket csak tőlünk lehet megtudni.

2021-03-14 13:20 UTC, Sumakolo submitted a review, later dismissed

2021-03-14 13:38 UTC, Montamy commented on src/AutomatedCar/Assets/reference_points.json
> -    "name": "road_2lane_rotary.png",
Az első Sprintre szükségünk volt ennek a file-nak az adataira, viszont a kommunikációs hibák - mi későn írtunk róla és valamiért nem ment róla értesítés - lemaradt a Worlodos oldalról, ezért mi a Visualizációs oldalon ezt pótoltuk magunknál. 
AutomatedCar.Visualization.WorldObjectTransformer osztályban van erre a fileban hivatkozásunk, "filename" alapján vesszük ki a hozzá tartozó ( vagy ha nem létezik 0,0) refererencia pontot "Vector" képében.

2021-03-14 13:43 UTC, vajnaivik approved these changes

2021-03-14 16:07 UTC, kuklinistvan commented on src/AutomatedCar/Assets/reference_points.json
> -    "name": "road_2lane_rotary.png",
Ha jól értem, akkor ezt javítanunk kell úgy, hogy a World-ből vegye ki ebben a PR-ban?

2021-03-15 10:10 UTC, pintergreg commented
Részemről mehet be, de @Montamy kommentje után tényleg szeretnék egy nagyon egyértelmű visszajelzést, hogy okoz-e nekik gondot a referenciapontok átírása.

2021-03-15 12:38 UTC, goet commented
> Részemről mehet be, de @Montamy kommentje után tényleg szeretnék egy nagyon egyértelmű visszajelzést, hogy okoz-e nekik gondot a referenciapontok átírása.

Ha az IRenderableWorldObject-en lesz a referenciapont akkor nincs már szükségünk arra a fájlra.

2021-03-15 12:44 UTC, goet requested changes

2021-03-15 12:44 UTC, goet commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
Egy WorldObject-nek csak egy referencia pontja lehet, amit kommentben írtam RefX/RefY vagy valami hasonló jobb lenne ide helyette.

2021-03-15 12:52 UTC, goet commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
Commitoltam az interface-t, ehhez alkalmazkodjon a WorldObject.

2021-03-15 13:24 UTC, goet commented
Szóval a BaseModel.WorldObject.RefX/Y-t töltsétek ki a megfelelő értékkel, aztán nekünk jó lesz.

2021-03-15 17:19 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
![kép](https://user-images.githubusercontent.com/19473224/111193589-99762480-85ba-11eb-99d8-e4dbedd11fa3.png)

Nem lesz ez így kicsit redundáns? :) A függvény, amit megjelöltél, nem a referencia pont lekérésére való - igazából nincs is vele dolgotok. Közvetlenül az alatt, amit megjelöltél, ott van, amit kérsz, lásd a képet. Ennek ellenére, szükségesek a property-k amik gyakorlatilag csak alias-olnák a Tuple<int, int> első és második tagját alatta?

2021-03-15 17:20 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
Még egy **fontos** kérdés: miért kell set-elni a referencia pontot? Úgy tudom, ez az objektum élete során nem változhat.

2021-03-15 17:21 UTC, kuklinistvan commented
> 
> 
> Szóval a BaseModel.WorldObject.RefX/Y-t töltsétek ki a megfelelő értékkel, aztán nekünk jó lesz.

Lásd fentebb: közvetlenül alatta van, amit odaírtál :) A lényegi különbség annyi, hogy nincsen rajta set, aminek nem is nagyon látnám az értelmét.

2021-03-15 17:23 UTC, goet commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
Nem, nem akarunk worldObject.ReferencePoint.item1-ként hivatkozni a ReferencePoint.X-re.

2021-03-15 17:29 UTC, kuklinistvan commented
![kép](https://user-images.githubusercontent.com/19473224/111194987-0e962980-85bc-11eb-8b11-1a6e28814b6b.png)

@Montamy, @pintergreg 
Amennyiben a Filename mező a vizualizációhoz tartozó png-t jelöli, akkor elvileg ezt nem tárolhatjuk le, lévén mi nem tudjuk, hogy hogyan fogtok vizualizálni. Ez körkörös függés lenne (ti függtök tőlünk, mint az alapmodelltől, mi függünk tőletek, mert alkalmazkodunk ahhoz, hogy png fájlokkal dolgoztok).

A helyes megoldás szerintem, ami ezt elkerülné, az az, hogy a Filename mező nélkül, egyéb módon - például egy mapping-gel - keresnétek ki a megfelelő png-t. (tile-os roguelike játékok is tipikusan így szoktak működni a legjobb tudomásom szerint - az egyes elemekhez a modellben nem tartoznak megjelenítésre vonatkozó információk, csak egyértelmű típus azonosítók)

2021-03-15 17:32 UTC, goet commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
Tuple-os szórakozás helyett ha Pointot használnátok, vagy definiálnátok egy saját osztályt erre akkor amúgy az egész try catches szórakozásra nem lenne szükség. :)

2021-03-15 17:39 UTC, goet approved these changes

2021-03-15 17:39 UTC, goet commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public int RefY { get => ReferencePoint.Item2;  }
Legutóbbi commitom, ennyit akartunk.

2021-03-15 18:11 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public int RefY { get => ReferencePoint.Item2;  }
Ha ez ennyire zavaró, részemről legyen :)

2021-03-15 18:12 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
> Tuple-os szórakozás helyett ha Pointot használnátok, vagy definiálnátok egy saját osztályt erre akkor amúgy az egész try catches szórakozásra nem lenne szükség. :)

Ezt kifejted, kérlek?

2021-03-15 18:13 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public int RefY { get => ReferencePoint.Item2;  }
Legutóbbi commit: látom, hogy a set kikerült, így ok.

2021-03-15 18:15 UTC, kuklinistvan commented on src/BaseModel/WorldObjects/WorldObject.cs
> +        public Dictionary<Type, Tuple<int, int>> ReferencePointDictionary { private get; set; }
> Nem, nem akarunk worldObject.ReferencePoint.item1-ként hivatkozni a ReferencePoint.X-re.

Részünkről rendben.

2021-03-15 18:15 UTC, kuklinistvan commented
@goet @pintergreg A Filename-dologról még beszéljünk, mert szerintem sérti az architektúrát (lásd: fentebb).

2021-03-16 09:14 UTC, pintergreg commented
@kuklinistvan Igen, értem a problémádat. Nem is zavar ebből a szempontból, hogy leszedtétek a kiterjesztést.

Azt a helyzetet szerettem volna elkerülni, hogy más is olvassa azt a fájlt, és épít arra, hogy ott van benne a kiterjesztés.
Azzal együtt is, hogy elméletileg nem is kellene másnak ahhoz a fájlhoz nyúlnia.

Ha valamilyen oknál fogva mégis közvetlenül akarna dolgozni más csapat azzal a fájlal, akkor is kétféleképpen oldható fel a helyzet:

1. ti nem módosítjátok a fájlt, csak a deszerializálás során levágjátok a kiterjesztést
2. aki mégis olvassa a fájlt hozzácsapja a kiterjesztést

_Mindkét esetben feltételezve, hogy a fájlneveket használja mindenki azonosítónak, hiszem mindenhol azok szerepelnek._

Ezek elméleti opciók, szerintem rendben van így. Az egyetlen ok ami miatt szemet szúrt a fájlt módosítása, hogy biztosra menjek abban, hogy senki más nem épít a kiterjesztés jelenlétére a fájlban.

---

Át lehet írni a Filename mezőt ImageID-ra is, meg a Filename mezőt is lehet azonosítónak tekinteni, vagy a kiterjesztéssel ellátott fájlnevet is lehet azonosítónak használni. Asszem ebben a sorrendben lesz egyre csúnyább a dolog.

Ami nekem nem világos, hogy van-e a mostani állapottal bárkinek problémája. @goet jóváhagyásából arra gondolok, hogy nincs.
Remélem megfelelő sorrendben olvasom az értesítéseimet és nem maradt ki semmi infó akkor mikor ezt írom.

2021-03-16 09:14 UTC, pintergreg approved these changes

2021-03-16 10:05 UTC, kuklinistvan commented
@pintergreg Köszönjük! Még egy apróság: tekintve, hogy minden azonos típusú objektum ugyanúgy jelenik meg, én feleslegesnek tartom az `ImageID` mező felvételét. Azt gondolom, hogy erre (is) lehet használni a `WorldObject.Type`-ot. Szerintem a vizualizálásnak erről kell leképeznie a fájlnevet. Mit gondolsz erről?

2021-03-16 11:33 UTC, Sumakolo approved these changes

2021-03-16 12:02 UTC, kuklinistvan commented
Ha senkinek nincsen ellenvetése, akkor ez mehet be szerintem.

2021-03-16 13:51 UTC, merged

2021-03-16 13:57 UTC, pintergreg commented
> Azt gondolom, hogy erre (is) lehet használni a `WorldObject.Type`-ot. Szerintem a vizualizálásnak erről kell leképeznie a fájlnevet. Mit gondolsz erről?

Simán működhet, de az ott nagybetűs. A fájlnevek és a JSON-ök kulcsai kisbetűsek, ha ez harmonizálva van, vagy le van fektetve szabályként, hogy át kell alakítani, esetleg a modell interfésze ezt kezeli, akkor jó: megszüntet egy redundanciát.

Erre a kérdésre nyitnék egy új (kis prioritású) issue-t bevonva az érintett csapatokat, ha konszenzus van, akkor új PR, stb.