Háromszög szenzor API
SzFMV2021-Tavasz/AutomatedCar-A pull request #111
Opened 2021-03-11 10:42 UTC by kuklinistvan

Megoldja: #106

2021-03-11 11:40 UTC, goet requested changes

2021-03-11 11:40 UTC, goet commented on src/BaseModel/Triangle.cs
> +    public class Triangle: Tuple<Tuple<int, int>, Tuple<int, int>, Tuple<int, int>>
Szerintem Tuple<int,int>x3 leszármazás helyett tisztább lenne a beépíttett Point osztályokat használni propertyként, és a konstruktorban csak azokat felülírni.

2021-03-11 11:40 UTC, goet commented on src/BaseModel/Triangle.cs
> +        public Triangle(int p0X, int p0Y, int p1X, int p1Y, int p2X, int p2Y) : base(new Tuple<int, int>(p0X, p0Y),
Lásd a felső, és akkor nem kell ilyen konstruktorokat hívni.

2021-03-11 11:42 UTC, goet commented
Apróság, de ha azt írod hogy "Resolves #106" akkor a github automatikusan összeköti az issue-val, és akkor amikor draftról élőre teszed a PR-t az issue automatikusan követni fogja a PR státuszát.

2021-03-24 16:42 UTC, vajnaivik approved these changes

2021-03-24 18:50 UTC, Sumakolo submitted a review, later dismissed

2021-03-25 09:35 UTC, pintergreg approved these changes

2021-03-25 09:36 UTC, pintergreg commented
@SzFMV2021-Tavasz/team-a2 

```

<<<<<<< gh-106_triangle-sensor-api
        private Tuple<int, int>[] _pointsAsTuple;
=======
        public bool Collidable => Type == Type_t.STANDALONE;  
>>>>>>> master
```
Mindkét sor kell, igaz?

2021-03-25 09:43 UTC, kuklinistvan commented
> 
> 
> @SzFMV2021-Tavasz/team-a2
> 
> ```
> 
> <<<<<<< gh-106_triangle-sensor-api
>         private Tuple<int, int>[] _pointsAsTuple;
> =======
>         public bool Collidable => Type == Type_t.STANDALONE;  
> >>>>>>> master
> ```
> 
> Mindkét sor kell, igaz?

@pintergreg Igen - sorry, nem oldottuk fel a conflict-okat.

2021-03-25 18:09 UTC, kuklinistvan commented
@pintergreg merge-eltem, ráteszed a master-re?

2021-03-25 19:34 UTC, merged