add IDisplaySensor
SzFMV2021-Tavasz/AutomatedCar-A pull request #128
Opened 2021-03-15 15:54 UTC by Montamy

- add interface of sensor displaying
- follow in AutomatedCar
- follow in MainWindow.xaml.cs
- add CamerSensor
- refactor displaying of Sensores

2021-03-15 16:10 UTC, goet approved these changes

2021-03-16 09:20 UTC, pintergreg approved these changes

2021-03-16 16:02 UTC, pintergreg commented
@Montamy azóta, hogy jóváhagytam csak a masterből jött merge, nem.
Nem tudom akkor miért nem fogadtam el, de nem látok okot, hogy miért ne mehetne be.

2021-03-16 19:42 UTC, goet approved these changes

2021-03-16 23:25 UTC, Montamy commented
Szerintem is mehet be.

2021-03-17 00:15 UTC, goet approved these changes

2021-03-17 07:47 UTC, szabogaliakos requested changes

2021-03-17 07:47 UTC, szabogaliakos commented on src/AutomatedCar/MainWindow.xaml.cs
> +            List<IDisplaySensor> cameraSensores = new List<IDisplaySensor>();
Sensores -> *Sensors

2021-03-17 07:47 UTC, szabogaliakos commented on src/AutomatedCar/MainWindow.xaml.cs
> +            List<IDisplaySensor> radarSensores = new List<IDisplaySensor>();
Sensores -> *Sensors

2021-03-17 07:47 UTC, szabogaliakos commented on src/AutomatedCar/MainWindow.xaml.cs
> +            List<IDisplaySensor> sonicSensores = new List<IDisplaySensor>();
Sensores -> *Sensors

2021-03-17 07:47 UTC, szabogaliakos commented on src/AutomatedCar/MainWindow.xaml.cs
> +            controlledCar.Video = cameraSensores;
Ha konzisztensek akarunk lenni akkor magyarul kamera szenzor, angolul video sensor. Legalábbis a handout szerint https://szfmv2021-tavasz.github.io/handout/software.html.

2021-03-17 07:47 UTC, szabogaliakos commented on src/AutomatedCar/MainWindow.xaml.cs
> +            cameraSensores.Add(new CameraSensor() { x1 = new Point(54, 120), x2 = new Point(0, -120), x3= new Point(108, -120) });
Nálam eltöri a buildet. Hiányzik a virtualFunctionBus a konstruktórból.

2021-03-17 08:28 UTC, szabogaliakos approved these changes

2021-03-17 11:58 UTC, pintergreg commented
@SzFMV2021-Tavasz/team-a4 Azóta lett egy fájlban ütközés (lehet, hogy a #128 miatt), a 2. és 3. triviális, az első viszont nem; melyik verziót kell megtartani?
Én azt mondanám első blikkre, hogy mindkettőt, így egymás alatt nem néz ki rosszul.

2021-03-17 13:09 UTC, szabogaliakos commented
Feloldottam a conflictokat. Refactoráltuk a kódot, ezért csak az egyik kellett. @pintergreg

2021-03-17 14:42 UTC, pintergreg approved these changes

2021-03-17 14:44 UTC, merged