Added world serialization to- and from json files
SzFMV2021-Tavasz/AutomatedCar-A pull request #16
Opened 2021-02-27 20:08 UTC by vajnaivik

2021-02-28 09:09 UTC, kuklinistvan requested changes
Alapvetően egy kisebb és egy nagyobb gondot találtam:
* A kisebb a kód-duplikálás a switch-case-nél, de ez viszonylag kis költséget okoz később, talán így is maradhat.
* A nagyobb, az az, hogy a WorldObject-jeink módosultak a JSON miatt, holott annak elvileg semmilyen módon nem kellene erről tudnia.

2021-02-28 09:09 UTC, kuklinistvan commented on BaseModel/World.cs
> +        [JsonProperty("width")]
Ajjaj. Bocsi, de szerintem ez itt ne maradjon így. A `World`, mint entity, nem tudhat arról, hogy honnan olvassuk be.
Olyat lehet, hogy a JSON beolvasód kiad egy World-öt, vagy WorldObject-eket.

Ronda kötekedő alak vagyok:
* Most már a World-nek két felelőssége van: az egyik, hogy egységes modell objektumokat adjon mindenkinek, a másik, hogy a JSON tartalmának megfeleljen. (SOLID S betű)
* Hirtelen a mi entity objektumaink függenek a JSON betöltőtől, holott szerintem a világmodell alapvetőbb komponens, amit holmi szerializálásért nem biztos, hogy szemetelnünk kellene, (SOLID D betű). Ebben a felállásban a `World` függ a betöltőtől, szerintem pedig inkább a betöltőnek kellene alkalmazkodni a világmodellhez.

2021-02-28 09:09 UTC, kuklinistvan commented on BaseModel/WorldObjects/WorldObject.cs
> +        [JsonIgnore]
Szerintem az összes ilyet ki kellene venni innen, és minden JSON-specifikus dolgot (lásd fentebb).

Konvertáló objektumokat viszont "szabad" használni - azaz egy olyan objektumkészletet, ami megfelel a JSON-ban lévőknek. A lényeg, hogy az eredeti világmodell a JSON kedvéért ne módosuljon.

2021-02-28 09:11 UTC, kuklinistvan commented
Természetesen, köszönöm a munkát, amit beletettél ;)

2021-02-28 14:20 UTC, Easimer requested changes

2021-02-28 14:20 UTC, Easimer commented on BaseModel/JsonHelper/WorldConverter.cs
> +                else if (reader.TokenType == JsonToken.PropertyName && reader.ReadAsString() == "width")
Nem találtam ehhez a konverterhez tesztet, de szerintem ez a rész nem fog rendesen működni. A `JsonReader.ReadAsString` az nem csak szimplán visszaadja a jelenlegi tokent, hanem preinkrementálja az olvasót. Ennek eredményeképp a kód egyáltalán nem fogja se a szélességet, se a magasságot beolvasni.

Tegyük fel épp a `"height"` kulcsra mutat az olvasó és épp kiértékelődik a
`reader.TokenType == JsonToken.PropertyName && reader.ReadAsString() == "width"`
feltétel.
A `ReadAsString` lépteti az olvasót és visszaadja a következő tokent, ami a `height` értéke, azaz az egyenlőség nem teljesül.
Ezután már végképp el van csúszva az olvasó és sose fog se a width-es, se a height-os feltétel teljesülni.

A fix erre annyi, hogy azt ugyanazt csinálod mint a legelső feltételben (L29):
`reader.TokenType == JsonToken.PropertyName && (string)reader.Value == "objects"`

2021-02-28 14:20 UTC, Easimer commented on BaseModel/JsonHelper/WorldConverter.cs
> +                // var debug = reader.Value;
Pár debug változó bent maradt; lentebb még van három hasonló: L159, L162, L164 (amúgy erre van a Watch ablak).

2021-03-01 19:27 UTC, vajnaivik commented on BaseModel/JsonHelper/WorldConverter.cs
> +                // var debug = reader.Value;
Ez jól benne maradt, köszi :D

2021-03-01 19:29 UTC, vajnaivik commented on BaseModel/JsonHelper/WorldConverter.cs
> +                else if (reader.TokenType == JsonToken.PropertyName && reader.ReadAsString() == "width")
Nagyon jó észrevétel, fel sem tűnt hogy 0 volt beolvasás után mindkettő. Köszi!

2021-03-01 19:36 UTC, vajnaivik commented on BaseModel/JsonHelper/WorldConverter.cs
> +                            case "2_crossroad_1":
Van jobb ötletem is rá talán, később még futok egy kört vele.

2021-03-01 19:57 UTC, vajnaivik commented on BaseModel/World.cs
> +        [JsonProperty("width")]
A json tartalmának csak annyira kell megfelelnünk, hogy betöltődjenek az objektumok. Tudtommal ez nem fog változni.

Nem tudom mi számít annak hogy a world mikor "tud" arról hogy hogyan olvassuk be, ez megérzésre nem.

Lehetne plusz objektumkészlet is illesztésként, lehet egyet is értenék ha a json később változhatna, bár akkor is szívesebben változtatnék meg pár attribútumot, mint az attribútumokat egy betöltő objektumon, a betöltő objektum struktúráját és a betöltő logikát is egy egy féléves tárgy kereteiben.

2021-03-01 20:15 UTC, kuklinistvan commented on BaseModel/World.cs
> +        [JsonProperty("width")]
Egyetértek, maradjon most

2021-03-02 18:25 UTC, kuklinistvan commented on BaseModel/World.cs
> +        [JsonProperty("width")]
> Nem tudom mi számít annak hogy a world mikor "tud" arról hogy hogyan olvassuk be, ez megérzésre nem.

Az attribútumok az osztályban. De maradjon, lehet, hogy jobb így. Valóban, így egyszerűbb.

2021-03-02 19:00 UTC, kuklinistvan commented
Utólagos engedelmeddel ebbe a PR-ba besegítek ;) Megjavítottam a rád vonatkozó teszteket.

2021-03-02 19:01 UTC, merged