Npc document path gen a3
SzFMV2021-Tavasz/AutomatedCar-A pull request #165
Opened 2021-03-29 14:19 UTC by Bszaben23

Implementálva lett az NPCDocumentPathGenerator osztály a #7 issue-ban lévő diagram alapján.
A Test projekthez hozzá lettek adva fájlok a beolvasás tesztelésének céljából.

2021-03-29 14:30 UTC, Easimer requested changes
A tesztek nem futnak le, mert az AutomatedCarTest projektben nincs a tesztfájlokon a _Copy to Output Directory_ property beállítva _Copy always_-re.

2021-03-29 14:30 UTC, Easimer commented on src/AutomatedCar/Models/NPCDocumentPathGenerator.cs
> +        public FileStream GetInputSteamOfNpcDocumentForWorld(string worldPath)
```suggestion
        public FileStream GetInputStreamOfNpcDocumentForWorld(string worldPath)
```

2021-03-29 14:30 UTC, Easimer commented on test/AutomatedCarTest/Models/NPCDocumentPathGeneratorTests.cs
> +        public void ReadsTheCorrectNPCPathDocument(string worldpath)
Az NPCDocumentPathGenerator-ön az útvonal kiszámítását át lehetne rakni egy külön függvénybe és akkor elég azt tesztelni, hogy a visszaadott útvonal helyes-e.

2021-03-29 14:30 UTC, Easimer commented on test/AutomatedCarTest/Models/NPCDocumentPathGeneratorTests.cs
> +            FileStream str = pathGen.GetInputSteamOfNpcDocumentForWorld(worldpath);
```suggestion
            FileStream str = pathGen.GetInputStreamOfNpcDocumentForWorld(worldpath);
```

2021-03-29 14:45 UTC, Bszaben23 commented on test/AutomatedCarTest/Models/NPCDocumentPathGeneratorTests.cs
> +        public void ReadsTheCorrectNPCPathDocument(string worldpath)
> Az NPCDocumentPathGenerator-ön az útvonal kiszámítását át lehetne rakni egy külön függvénybe és akkor elég azt tesztelni, hogy a visszaadott útvonal helyes-e.

Ezt most nem teljesen értem. NPCDocumentPathGenerator nem számol semmit, csak visszaadja az Npc útvonalakat leíró dokumentumot FileStream-ként.

2021-03-29 17:54 UTC, Easimer commented on test/AutomatedCarTest/Models/NPCDocumentPathGeneratorTests.cs
> +        public void ReadsTheCorrectNPCPathDocument(string worldpath)
Annyi hogy a "Path.Combine(Path.GetDirectoryName(worldPath), Path.GetFileNameWithoutExtension(worldPath) + ".npcs.yaml")" rész mehetne egy külön függvénybe és akkor tesztelhető lenne az útvonal létrehozása.

2021-03-29 18:36 UTC, Bszaben23 commented on test/AutomatedCarTest/Models/NPCDocumentPathGeneratorTests.cs
> +        public void ReadsTheCorrectNPCPathDocument(string worldpath)
Így már értem, mindjárt átírom akkor.

2021-03-30 06:39 UTC, Easimer approved these changes

2021-03-30 11:13 UTC, pintergreg approved these changes

2021-03-30 11:13 UTC, merged