Npc deserialization a3
SzFMV2021-Tavasz/AutomatedCar-A pull request #168
Opened 2021-04-03 22:53 UTC by kissamon

A kívülről érkező yaml fájl tartalmának beolvasása és az adatokból npc objektumok létrehozása.

2021-04-04 08:34 UTC, Easimer requested changes

2021-04-04 08:34 UTC, Easimer commented on src/AutomatedCar/Models/YamlNpcDocumentLoader.cs
> +                    n.Position = new Vector2(x, y);
A path node 'pos' tulajdonsága nem egy string amit kézzel kéne feldolgozni, hanem egy sima mapping.
```suggestion
                    var nodePos = node["pos"] as YamlMappingNode;
                    var nodeX = nodePos["x"] as YamlScalarNode;
                    var nodeY = nodePos["y"] as YamlScalarNode;
                    var x = float.Parse(nodeX.Value, CultureInfo.InvariantCulture.NumberFormat);
                    var y = float.Parse(nodeY.Value, CultureInfo.InvariantCulture.NumberFormat);
                    n.Position = new Vector2(x, y);
```

2021-04-04 11:50 UTC, Easimer approved these changes

2021-04-04 14:00 UTC, Bszaben23 approved these changes

2021-04-06 07:21 UTC, pintergreg approved these changes

2021-04-06 07:21 UTC, merged